name: Go CI/CD with Docker

on:
  push:
    branches:
      - infrastructure
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Build Docker image
        run: docker build -t tungluea-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push tungluea-image

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: go build -v ./...

      - name: Build Docker image
        run: docker build -t tungluea-back .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push tungluea-back

      - name: Deploy to Docker service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_SERVER_HOST }}
          username: ${{ secrets.DOCKER_SERVER_USERNAME }}
          password: ${{ secrets.DOCKER_SERVER_PASSWORD }}
          port: ${{ secrets.DOCKER_SERVER_PORT }}
          script: |
            docker pull your-image-name
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d --name your-container-name -p 8080:3000 your-image-name
